### ISSUE TITLE
ios7 inobounce break scrolling

### ISSUE THREAD

**Issue by dook0** [lazd/iNoBounce#11]
Everything work fine in ios8, but nothing scrolls on ios7 (ios7.1.2 in my case).

**Comment by dook0** [comment]
my bad 
<meta name="apple-mobile-web-app-capable" content="yes"> 
seems to break the scrolling on ios7....

**Comment by lazd** [comment]
@dook0 do you still have an issue? I don't understand what you mean by "seems to break the scrolling on ios7....".
![screen shot 2015-02-13 at 10 23 35 am](https://cloud.githubusercontent.com/assets/201344/6192816/ab15adc4-b36a-11e4-9580-6d73eb7284da.png)

I just tested on iOS 7.1 in the iOS simulator and things are working perfectly. When I wrote iNoBounce, I was also testing against iOS 6 and then iOS 7 in later usages and never had problems.

**Comment by lazd** [comment]
@dook0 please test this page on your iOS 7 device and let me know if it scrolls: http://blog.lazd.net/iNoBounce/

**Comment by dook0** [comment]
hi thank you it works.
I think my issue is not related with this plugin :)
thank you !

**Comment by lazd** [comment]
>  meta name="apple-mobile-web-app-capable" content="yes" seems to break the scrolling on ios7....

@dook0 there must be something else in play. The example I linked to has that meta tag and works perfectly in iOS 7 in both Safari and as a homescreen webapp. Furthermore, [VisualStager](http://app.visualstager.com) uses iNoBounce and works perfectly.

Let me know when you find out what is causing this problem -- even if it's not with the plugin, things that break the plugin need to be documented. Thanks!

**Comment by dook0** [comment]
the culprit was : bind("scroll")
It doesn't work on iOS7... I missed that.

**Comment by lazd** [comment]
It sounds like you were doing a `preventDefault()` on `scroll`, which will certainly stop scrolling.

Glad to know you found the problem!
