### ISSUE TITLE
Rubber scrolling is still on when scroll is still on momentum

### ISSUE THREAD

**Issue by gitlovenotwar** [lazd/iNoBounce#18]
Hi,

The rubber scrolling is still showing when scrolls is still on momentum. It works when the scroll is on the top at rest but when you scroll down and then back to the top most part while still on momentum it's not working anymore.

**Comment by lazd** [comment]
That's by design, the *page itself* shouldn't rubberband, but the scroll area should.

Please see https://github.com/lazd/iNoBounce/issues/17#issuecomment-146625798

If this does not clear things up for you, please re-open this issue.

**Comment by gitlovenotwar** [comment]
I guess that's how the plugin works. Is there a way or add it the way I described it?
