### ISSUE TITLE
Does not work on bootstrap themes

### ISSUE THREAD

**Issue by saulob** [lazd/iNoBounce#25]
I'm trying to disable bounce using bootstrap and a bootstrap theme but everything stop scrolling not just the bounce.

What's wrong?

**Comment by lazd** [comment]
I see this is your first interaction with Github. Generally, when filing an issue for a project like this, it's best practice to include a link to a repository that reproduces the issue. Given the information provided, I can't help you. Please feel free to re-open this issue once you've created a repository that illustrates the issue. You may publish this to [GitHub pages](https://pages.github.com/) and provide the URL so I can easily test your issue.
