### ISSUE TITLE
Enable zooming in iOS whilst keeping scrolling/bouncing disabled

### ISSUE THREAD

**Issue by rorysmorris** [lazd/iNoBounce#26]
0
down vote
favorite
I'm creating a web-app for iOS Safari and have run into a slight hurdle.

My web-app only takes up 1024x768 of screen real estate and therefore does not need scrolling, but it does need to be able to zoom (it's a PDF annotator).

I have used a plugin called iNoBounce (https://github.com/lazd/iNoBounce/) which successfully removes scrolling from the page by firing an evt.preventDefault() on the touchmove/touchstart events. This is great.

What this does though, is remove zoom events as well as scroll events. Is there a way to remove scrolling/elastic bouncing but to retain zoom on iOS safari?

Many thanks

---

I've managed to fix this issue, details here: http://stackoverflow.com/questions/37611300/ios-safari-disable-scroll-bounce-but-retain-zoom/37612533#37612533

**Comment by lazd** [comment]
Interesting! I'd accept a pull request for this. Have you tried the other examples in this repo to make sure it doesn't break them?

**Comment by lazd** [comment]
@rorysmorris please send along a PR so we can get your fix into the library!
