### ISSUE TITLE
Doesn't take into account all values for overflow

### ISSUE THREAD

**Issue by jinder** [lazd/iNoBounce#3]
Hi - nice little library!

I was having a few issues, and realised that your library isn't taking into account all possible overflow/overflow-y values to determine whether a particular element scrolls.  Adding the following fixes it:

```
var overflowY = style.getPropertyValue('overflowY');
```

```
// Determine if the element should scroll
var isScrollable = scrolling === 'touch' && (overflow === 'auto' || overflow === 'scroll' || overflowY === 'auto' || overflowY === 'scroll');
```

Thanks!

**Comment by lazd** [comment]
This was actually closed by https://github.com/lazd/iNoBounce/commit/313c4813c74983999da814bceb05768d6aec4ad2.
