### ISSUE TITLE
Latest fix for ios 11.3 breaks Chrome

### ISSUE THREAD

**Issue by asos-martiplanellas** [lazd/iNoBounce#48]
Something done on the latest release completely disables scrolling everywhere on Chrome

**Comment by qiqakotyi** [comment]
Same issue , had to downgrade.

**Comment by lazd** [comment]
Hmmmm. Any errors at all?

These were the only changes, they seem minimal: https://github.com/lazd/iNoBounce/pull/47/files

**Comment by asos-martiplanellas** [comment]
I suspect is because of the way the `touchstart` events are attached, from my point of view and since this whole library is targeted at Safari, these events should only be attached if the _browser supports -webkit-overflow-scrolling_ rule is true. Which is what I've done to fix this issue on my code:

```
const needsBounceEffect = () => {
  const testDiv = document.createElement("div");
  document.documentElement.appendChild(testDiv);
  testDiv.style.WebkitOverflowScrolling = "touch";
  const scrollSupport =
    "getComputedStyle" in window &&
    window.getComputedStyle(testDiv)["-webkit-overflow-scrolling"] === "touch";
  document.documentElement.removeChild(testDiv);
  return scrollSupport;
};
...
if (needsBounceEffect()) {
  BounceEffect.enable();
}

```

**Comment by lazd** [comment]
@asos-martiplanellas but that code is already present: https://github.com/lazd/iNoBounce/blob/master/inobounce.js#L97-L108

**Comment by asos-martiplanellas** [comment]
@lazd yes, but not on the `enable` method. My point is that, this check should be in place when you call `enable` and not attach the listeners unless is needed.

**Comment by asos-martiplanellas** [comment]
@lazd the reason why I have an explicit `enable` call is because I have a responsive site (I assume most people do), but I only want to trigger this behaviour on mobile, but not on desktop. 

As it stands, your code will enable itself automatically for both desktop and mobile, and that is not the behaviour I want.

**Comment by lazd** [comment]
@asos-martiplanellas that's fair, though on desktop, there are no touch events being triggered, so it won't do anything -- the page actually still bounces in both Chrome and Safari when scrolling with multitouch, whether it's enabled or disabled, so it doesn't alter the behavior at all.

That said, though I don't think that removing "enable automatically" is the answer as that's a breaking change, but I would be open to a more robust check that makes sure you're on a touch device before trying to enable itself.

**Comment by asos-martiplanellas** [comment]
@lazd removing "enable automatically" is *not* the solution I'm proposing.

The solution I'm proposing is for the `enable` function to do feature check before attaching the event listeners.

**Comment by greggman** [comment]
> though on desktop, there are no touch events being triggered

Desktops have touch, at least on Windows

**Comment by lazd** [comment]
> And also, the "there are no touch events on desktop" is quite naive I think, there are plenty of laptops with touch screen.

@asos-martiplanellas are you testing on a touch screen laptop in Chrome? Does iNoBounce do anything there, or are you simply pointing out that touch screen laptops exist?

**Comment by lazd** [comment]
I'm not seeing any errors in Chrome with iNoBounce enabled, even when emulating devices. I'll close this for now.
