### ISSUE TITLE
Doesn't work in iOS 11.3.1?

### ISSUE THREAD

**Issue by greggman** [lazd/iNoBounce#51]
none of the demos seem to prevent scrolling in Safari on iOS 11.3.1

In particular for me the Touchscreen Drawing Example scrolls while drawing. I'm guessing this is a bug in Safari? Not sure though

**Comment by hg-pyun** [comment]
I have a same issue. iOS 11.3

**Comment by lazd** [comment]
The examples hadn't been deployed for like, 4 years. I redeployed them with an updated version of iNoBounce, I trust you'll find they all work now (I tested on iOS 11.3.1). http://blog.lazd.net/iNoBounce/

Thanks for the heads up, and feel free to re-open this issue if it still doesn't work.
