### ISSUE TITLE
Window.getComputedStyle must be an instance of Element on iOS 11.3

### ISSUE THREAD

**Issue by mokkymiah** [lazd/iNoBounce#52]
I am getting the following error with our application when running iOS 11.3;

```js
getComputedStyle@[native code]
r@https://localhost:8000/app.js:26:109    

message: Argument 1 ('element') to Window.getComputedStyle must be an instance of Element
```

Is there a fix for this? We are running iNoBounce version 0.1.6

**Comment by lazd** [comment]
Hmm, I'd have to see some sample code that reproduces the issue. What element is it throwing on? There is a tree traversal that is supposed to stop at the `<body>` or document: https://github.com/lazd/iNoBounce/blob/master/inobounce.js#L28

**Comment by lazd** [comment]
Also, are you only seeing this error in iOS 11.3? Have you tried iNoBounce demos in iOS 11.3 and reproduced the issue? http://blog.lazd.net/iNoBounce/

**Comment by terpro** [comment]
I'm getting this same issue on iOS 12 beta 5. Only happens when the page initially loads, and only sometimes.

"Type Error: Argument 1 ('element') to Window.getComputedStyle must be an instance of Element" on line 28

**Comment by lazd** [comment]
Not seeing this on iOS 12.2 with the demo pages here http://blog.lazd.net/iNoBounce/, closing this.
