### ISSUE TITLE
Prevents Vertical Scrolling on Android

### ISSUE THREAD

**Issue by rafecolton** [lazd/iNoBounce#57]
On Android 8.1, this breaks scrolling

**Comment by lazd** [comment]
On the default browser? What about other browsers?

Also, please confirm that this page doesn't work: http://blog.lazd.net/iNoBounce/

**Comment by rafecolton** [comment]
On the default browser, yes. I am currently testing on the simulator, so I cannot install other browsers, however the original issue was confirmed on a real device.

I am really only concerned about the default browser—I assume the majority of people on any mobile device will use the default browser.

As far as I can tell, the page you provided is working. [Here](https://dev.himalayaninstitute.org/year-long-meditation/#/p/a/track?d=today&v=day) is my site in dev if you'd like to see it and test it. You'll have to create a free account, so feel free to use a bogus name and email address. The element with `-webkit-overflow-scrolling: touch;` is `.PortalOverlay`

**Comment by lazd** [comment]
Unfortunately, if the page I linked to is working, then you'll have to provide a simplified example with only the bare minimum code required to reproduce the issue. Please create a codepen/fiddle or a repo with a `gh-pages` brach reproducing the bug and re-open the issue when you have that.
