### ISSUE TITLE
Enable zooming in iOS whilst keeping scrolling/bouncing disabled (2)

### ISSUE THREAD

**Issue by rafecolton** [lazd/iNoBounce#58]
This is a continuation of #26 which is still an issue on iOS 12.2. Verified on http://blog.lazd.net/iNoBounce/

Zooming isn't disabled entirely, but it is difficult to use and not nearly as smooth. You can compare [here](https://staging.himalayaninstitute.org/year-long-meditation/#/p/login) (iNoBounce enabled) to [here](https://dev.himalayaninstitute.org/year-long-meditation/#/p/login) (iNoBounce disabled)

**Comment by lazd** [comment]
Try 0.2.0 please, that should fix it. If you still have problems zooming, please go ahead and reproduce them on the included example files, then re-open this issue.
