### ISSUE TITLE
package support?

### ISSUE THREAD

**Issue by jasonkuhrt** [lazd/iNoBounce#6]
Are you open to a PR that would provide package support for component? Happy to oblige if so.

**Comment by jasonkuhrt** [comment]
@lazd please see my PR. If you need help maintaining this repo feel free to add me as a collaborator.

**Comment by natew** [comment]
Would like to see this mantained, it's close to being a de-facto best usage package for hybrid apps. Let me know I can help as well.

**Comment by jasonkuhrt** [comment]
My confidence on this issue and future ones is lost. In the future we will fork and make an `npm` release ourselves.

**Comment by natew** [comment]
Let me know here if you please, if not I may do so at /reapp/inobounce

**Comment by lazd** [comment]
@jasonkurt, I'll take a look at the PR and merge tonight. Apologies for the delay, I'm insanely busy and absolutely could use help maintaining the package.

**Comment by jasonkuhrt** [comment]
@lazd Cool.

**Comment by lazd** [comment]
Closed by #10.

**Comment by lazd** [comment]
Published `inobounce@0.1.0` https://www.npmjs.com/package/inobounce

**Comment by jasonkuhrt** [comment]
@lazd Thank-you!
