### ISSUE TITLE
Breaks scrolling on iOS

### ISSUE THREAD

**Issue by stevenschmatz** [lazd/iNoBounce#70]
In your [example](http://blog.lazd.net/iNoBounce/) on iOS 14.2.1, the page cannot scroll whatsoever. However, when you click "disable" the page can scroll once more.

**Comment by lazd** [comment]
Yeah, it seems to be broken. #66, #67, #69. A couple PRs are in to try to fix it, but they defeat the purpose of the library (it bounces), see #65.

If you have a fix, I'll definitely review the PR. Please comment on the other issues in the meantime. Thanks!

**Comment by marcocryptoX** [comment]
I think the library should allow to lock the bounce on a master element and let childs to scroll freely
i want to use it in a whatsapp style app , so i need that the main div is locked and elements inside scroll as expected 
do you think it can be done with this lib?

**Comment by lazd** [comment]
@marcocryptoX that's sort of how it used to work when it worked.
